### PR TITLE
fix(avatar): show avatar fallback if no avatar image is provided

### PR DESCRIPTION
**Pull request by mrzachnugent**

### CODE REVIEW

**Comment by danstepanov** [comment]
@mrzachnugent what's the before/after on this? can you clarify?

**Comment by mrzachnugent** [comment]
@danstepanov 

The avatar component has 2 sub components: AvatarFallback and AvatarImage.

# Before
The AvatarFallback would only display when there was an error from the AvatarImage. This resulted in the AvatarFallback never showing up when the AvatarImage was not provided since it would never error.

# After
If the AvatarImage is not provided, the AvatarFallback is shown. If the AvatarImage is provided, the AvatarFallback is only shown when there is an error in loading the image.

**Comment by danstepanov** [comment]
Got it, should CES be updated with this code as well?

**Comment by mrzachnugent** [comment]
> Got it, should CES be updated with this code as well?

I thought the CLI would take care of this. Otherwise, yes it should be updated

**Comment by danstepanov** [comment]
CES isn't using the CLI yet, i'll chat with Sam

**Comment by danstepanov** [comment]
@mrzachnugent for now, whenever you make changes to component code, please send me a reference to the change so I can update the code in CES

**Comment by danstepanov** [comment]
@mrzachnugent I implemented these changes in CES and tried running the project again, it doesn't seem to fix the issue where the avatar does not show. Was this intended to fix that?

`npx create-expo-stack@next my-expo-app --nativewindui --selected-components=avatar --expo-router`

**Comment by mrzachnugent** [comment]
@danstepanov Just started a new CES project with the command you provided and it works on my end:


https://github.com/user-attachments/assets/3f547f52-7dba-4aba-b472-517559efde1c

**Comment by mrzachnugent** [comment]
@danstepanov This was a cache clearing issue on your end right?

**Comment by danstepanov** [comment]
Correct, `npx expo start -c`

Until we publish the new version of NativeWind v4, we should add this to the "Troubleshooting" section

**Comment by mrzachnugent** [comment]
@danstepanov In the docs? It's already there https://nativewindui.com/troubleshoot
Or in the script in the package.json? That's what the `dev` script does.

**Comment by danstepanov** [comment]
Oh perfect

**Review by danstepanov — APPROVED** [review]

**Pull request merged**
